### ISSUE TITLE
cannot connect to X server

### ISSUE THREAD

**Issue by mrocr** [PRHLT/Docker-UOBEL#1]
@vbosch 
**Note that I am new to Docker.**
After downloading and building this container successfully, I ran:
```
sudo docker run --rm -ti ba306fd26ab0
git clone https://github.com/PRHLT/pageDistanceBasedContourGenerator.git
cd pageDistanceBasedContourGenerator
make all
```

Finally, when testing, an error message appears: 
```
root@447043d6dbf8:/home/pageDistanceBasedContourGenerator# ./extract_lines -i 156730303.jpg -p 156730303.xml -o output.xml -w 4 -x -1
41 [0x7ff17ba24880] INFO Polyline_Extractor null - <<Instantiating POLYLINE EXTRACTOR>>
55 [0x7ff17ba24880] INFO Polyline_Extractor null - <<DONE>>
55 [0x7ff17ba24880] INFO Polyline_Extractor null - <<RUNNING WITH SEARCH AREAS>>
3832 [0x7ff17ba24880] INFO Polyline_Extractor null - SAVING DISTANCE MAP
3861 [0x7ff17ba24880] INFO Polyline_Extractor null - <<CALCULATING LINE FRONTIER>>
: cannot connect to X server 

```

**Comment by mrocr** [comment]
Using other parameters:
```
sudo docker run --rm -ti --entrypoint /bin/bash uobel-docker
```
```
root@edae8d80f5df:/home/pageDistanceBasedContourGenerator# ./extract_lines -i 156730303.jpg -p 156730303.xml -o output.xml -w 4 -x -1
139 [0x7f94c6402880] INFO Polyline_Extractor null - <<Instantiating POLYLINE EXTRACTOR>>
165 [0x7f94c6402880] INFO Polyline_Extractor null - <<DONE>>
165 [0x7f94c6402880] INFO Polyline_Extractor null - <<RUNNING WITH SEARCH AREAS>>
4477 [0x7f94c6402880] INFO Polyline_Extractor null - SAVING DISTANCE MAP
4515 [0x7f94c6402880] INFO Polyline_Extractor null - <<CALCULATING LINE FRONTIER>>
WARNING: QApplication was not created in the main() thread.
: cannot connect to X server 
Segmentation fault (core dumped)
```

**Comment by vbosch** [comment]
There was an issue regarding the calculation of the extraction frontiers
and the restrictions made by the baselines. It might sometimes happen
depending of the upper
and lower search area bounds you input via the command line (-u -l).

It will now show an error message instead of displaying graphically the
issue ( this why you got the x server issue in docker). If there is an
issue with the frontier calculation it will default to a standard
simplified solution. Let me know if it works for you.

Could you please let me know for which company or research group do you
work for ?

Regards,
V.

**Comment by mrocr** [comment]
Thank you for solving this issue so soon.
I am not affiliated with any research group, but I am interested in the development of OCR personally, for now.
